# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobra', '0002_initial_unions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['liu_id'], 'verbose_name': 'student', 'verbose_name_plural': 'students'},
        ),
        migrations.RenameField(
            model_name='student',
            old_name='id',
            new_name='nor_edu_person_lin',
        ),
        migrations.AlterField(
            model_name='student',
            name='nor_edu_person_lin',
            field=models.UUIDField(editable=False, help_text='Local identity number. It will never change and thus can be used to integrate with other systems also utilizing the norEduPersonLIN.', primary_key=True, serialize=False, verbose_name='norEduPersonLIN'),
        ),
    ]
